### ISSUE TITLE
Add button to cancel file upload process

### ISSUE THREAD

**Issue by omrishtam** [meateam/web-ui#12]
Lior asked for it 😁

**Comment by LiorHaim** [comment]
Can you just prepare the backend functionality for it?

**Comment by omrishtam** [comment]
> Can you just prepare the backend functionality for it?

The api-gateway [supports this already](https://github.com/meateam/api-gateway/pull/22), the client's ui just needs to have the ability to cancel the upload request, and the api-gateway would clean up what's already been uploaded **if the upload is resumable** (> 5 MB).

Because of the way the rest of the upload types (< 5 MB) request handlers are implemented, getting the whole file is a blocking operation, and metadata is only created for the file *after* its binary is fully received. So there should be no clean up needed for canceling the other types of upload.

**Comment by yonatandt** [comment]
Review issue again after we chose the next UI
