### ISSUE TITLE
Disable delete when dialog is open

### ISSUE THREAD

**Issue by yonatandt** [meateam/web-ui#76]
The UI should not act on a `Delete` key press when a dialog is open. 

Pressing on the `Delete` key when some files are selected and the dialog is open (for example the`edit` dialog), the UI is starting the deletion process (opening the delete dialog).

**Comment by omerzamir** [comment]
it's not a bug, it's a feature.

**Comment by yonatandt** [comment]
Even when editing a file's name?
Doesn't sound intuitive.
